export const ERROR = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZE: "UNAUTHORIZE",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_TYPE: "INVALID_TYPE",

  INVALID_EMAIL: "INVALID_EMAIL",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
  EMAIL_NOT_REGISTERED: "EMAIL_NOT_REGISTERED",

  USERNAME_REQUIRED: "USERNAME_REQUIRED",
  USERNAME_TOO_SHORT: "USERNAME_TOO_SHORT",
  USERNAME_TOO_LONG: "USERNAME_TOO_LONG",
  USERNAME_ALREADY_EXIST: "USERNAME_ALREADY_EXIST",
  INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",

  PASSWORD_SHOULD_CONTAIN_LOWERCASE: "PASSWORD_CONTAIN_LOWERCASE",
  PASSWORD_SHOULD_CONTAIN_UPPERCASE: "PASSWORD_CONTAIN_UPPERCASE",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_SHOULD_CONTAIN_NUMBER: "PASSWORD_CONTAIN_NUMBER",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_DONT_MATCH: "PASSWORD_DONT_MATCH",
  CONFIRM_PASSWORD_REQUIRED: "CONFIRM_PASSWORD_REQUIRED",

  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  NAME_TOO_SHORT: "NAME_TOO_SHORT",

  GENDER_REQUIRED: "GENDER_REQUIRED",
  INVALID_GENDER: "INVALID_GENDER",

  BIO_TOO_LONG: "BIO_TOO_LONG",

  INVALID_IMAGE_TYPE: "error.image.invalid_type",
  IMAGE_TOO_LARGE: "error.image.too_large",

  PROFILE_ALREADY_CREATED: "PROFILE_ALREADY_CREATED",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  COMPLETE_PROFILE_FIRST: "COMPLETE_PROFILE_FIRST",
  CREATE_PROFILE_FIRST: "CREATE_PROFILE_FIRST",

  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  INVALID_NOTIFICATION_TYPE: "error.settings.invalid_type",
  INVALID_TIME_FORMAT: "error.settings.invalid_time_format",
  INVALID_LANGUAGE: "error.settings.invalid_language",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_BLOCKED: "USER_ALREADY_BLOCKED",
} as const
