-- CreateEnum
CREATE TYPE "LogActivity" AS ENUM ('LOGIN', 'LOGOUT', 'RESET_PASSWORD', 'LOGIN_NEW_DEVICE', 'CREATE_PROFILE', 'UPDATE_PROFILE', 'UPDATE_SETTING', 'UPDATE_PRIVATE_CHAT_OPTION', 'CREATE_GROUP', 'UPDATE_GROUP', 'UPDATE_GROUP_OPTION', 'JOIN_GROUP', 'LEFT_GROUP', 'ADD_GROUP_MEMBER', 'REMOVE_GROUP_MEMBER', 'CREATE_CHANNEL', 'UPDATE_CHANNEL', 'UPDATE_CHANNEL_OPTION', 'SUBCRIBE_CHANNEL', 'UNSUBSCRIBE_CHANNEL', 'SEND_MESSAGE', 'UPDATE_MESSAGE', 'DELETE_MESSAGE', 'REACT_MESSAGE', 'BLOCK_USER', 'UNBLOCK_USER');

-- CreateTable
CREATE TABLE "user_logs" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "activity" "LogActivity" NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_logs_pkey" PRIMARY KEY ("id")
);
